package com.dipuguide.toolmate.ui.theme
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF0059BB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0070EA)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF405E96)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA4C1FF)
val onSecondaryContainerLight = Color(0xFF2F4E85)
val tertiaryLight = Color(0xFF8E2CB0)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAA49CC)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C23)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF181C23)
val surfaceVariantLight = Color(0xFFDDE2F4)
val onSurfaceVariantLight = Color(0xFF414754)
val outlineLight = Color(0xFF717786)
val outlineVariantLight = Color(0xFFC1C6D7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3039)
val inverseOnSurfaceLight = Color(0xFFEEF0FB)
val inversePrimaryLight = Color(0xFFADC7FF)
val surfaceDimLight = Color(0xFFD7D9E5)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F3FE)
val surfaceContainerLight = Color(0xFFEBEDF9)
val surfaceContainerHighLight = Color(0xFFE6E8F3)
val surfaceContainerHighestLight = Color(0xFFE0E2ED)

val primaryLightMediumContrast = Color(0xFF003473)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF0069DC)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF11356A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF4F6DA5)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF5C007A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFA141C3)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9FF)
val onBackgroundLightMediumContrast = Color(0xFF181C23)
val surfaceLightMediumContrast = Color(0xFFF9F9FF)
val onSurfaceLightMediumContrast = Color(0xFF0E1119)
val surfaceVariantLightMediumContrast = Color(0xFFDDE2F4)
val onSurfaceVariantLightMediumContrast = Color(0xFF303643)
val outlineLightMediumContrast = Color(0xFF4D5261)
val outlineVariantLightMediumContrast = Color(0xFF676D7C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3039)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEEF0FB)
val inversePrimaryLightMediumContrast = Color(0xFFADC7FF)
val surfaceDimLightMediumContrast = Color(0xFFC4C6D1)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF1F3FE)
val surfaceContainerLightMediumContrast = Color(0xFFE6E8F3)
val surfaceContainerHighLightMediumContrast = Color(0xFFDADCE7)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCFD1DC)

val primaryLightHighContrast = Color(0xFF002A60)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004697)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF012A60)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF29487F)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4D0066)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF780D9C)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9FF)
val onBackgroundLightHighContrast = Color(0xFF181C23)
val surfaceLightHighContrast = Color(0xFFF9F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDDE2F4)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF262C39)
val outlineVariantLightHighContrast = Color(0xFF434957)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3039)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFADC7FF)
val surfaceDimLightHighContrast = Color(0xFFB6B8C3)
val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF0FB)
val surfaceContainerLightHighContrast = Color(0xFFE0E2ED)
val surfaceContainerHighLightHighContrast = Color(0xFFD2D4DF)
val surfaceContainerHighestLightHighContrast = Color(0xFFC4C6D1)

val primaryDark = Color(0xFFADC7FF)
val onPrimaryDark = Color(0xFF002E68)
val primaryContainerDark = Color(0xFF4A8EFF)
val onPrimaryContainerDark = Color(0xFF001537)
val secondaryDark = Color(0xFFADC7FF)
val onSecondaryDark = Color(0xFF072F64)
val secondaryContainerDark = Color(0xFF29487F)
val onSecondaryContainerDark = Color(0xFF9BB8F6)
val tertiaryDark = Color(0xFFEEB0FF)
val onTertiaryDark = Color(0xFF53006E)
val tertiaryContainerDark = Color(0xFFC967EB)
val onTertiaryContainerDark = Color(0xFF2B003B)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131B)
val onBackgroundDark = Color(0xFFE0E2ED)
val surfaceDark = Color(0xFF10131B)
val onSurfaceDark = Color(0xFFE0E2ED)
val surfaceVariantDark = Color(0xFF414754)
val onSurfaceVariantDark = Color(0xFFC1C6D7)
val outlineDark = Color(0xFF8B90A0)
val outlineVariantDark = Color(0xFF414754)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2ED)
val inverseOnSurfaceDark = Color(0xFF2D3039)
val inversePrimaryDark = Color(0xFF005BC0)
val surfaceDimDark = Color(0xFF10131B)
val surfaceBrightDark = Color(0xFF363942)
val surfaceContainerLowestDark = Color(0xFF0B0E16)
val surfaceContainerLowDark = Color(0xFF181C23)
val surfaceContainerDark = Color(0xFF1C2027)
val surfaceContainerHighDark = Color(0xFF272A32)
val surfaceContainerHighestDark = Color(0xFF31353D)

val primaryDarkMediumContrast = Color(0xFFCEDCFF)
val onPrimaryDarkMediumContrast = Color(0xFF002454)
val primaryContainerDarkMediumContrast = Color(0xFF4A8EFF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCEDCFF)
val onSecondaryDarkMediumContrast = Color(0xFF002454)
val secondaryContainerDarkMediumContrast = Color(0xFF7391CC)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF7CFFF)
val onTertiaryDarkMediumContrast = Color(0xFF430059)
val tertiaryContainerDarkMediumContrast = Color(0xFFC967EB)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF10131B)
val onBackgroundDarkMediumContrast = Color(0xFFE0E2ED)
val surfaceDarkMediumContrast = Color(0xFF10131B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF414754)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD7DCED)
val outlineDarkMediumContrast = Color(0xFFACB2C2)
val outlineVariantDarkMediumContrast = Color(0xFF8B90A0)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE0E2ED)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF272A32)
val inversePrimaryDarkMediumContrast = Color(0xFF004595)
val surfaceDimDarkMediumContrast = Color(0xFF10131B)
val surfaceBrightDarkMediumContrast = Color(0xFF41444D)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF05070E)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1E25)
val surfaceContainerDarkMediumContrast = Color(0xFF242830)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2F323B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3A3E46)

val primaryDarkHighContrast = Color(0xFFECEFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA6C3FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000A22)
val secondaryDarkHighContrast = Color(0xFFECEFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA6C3FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000A22)
val tertiaryDarkHighContrast = Color(0xFFFFEAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFEDABFF)
val onTertiaryContainerDarkHighContrast = Color(0xFF190024)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF10131B)
val onBackgroundDarkHighContrast = Color(0xFFE0E2ED)
val surfaceDarkHighContrast = Color(0xFF10131B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF414754)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFECEFFF)
val outlineVariantDarkHighContrast = Color(0xFFBDC2D3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE0E2ED)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF004595)
val surfaceDimDarkHighContrast = Color(0xFF10131B)
val surfaceBrightDarkHighContrast = Color(0xFF4D5059)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1C2027)
val surfaceContainerDarkHighContrast = Color(0xFF2D3039)
val surfaceContainerHighDarkHighContrast = Color(0xFF383B44)
val surfaceContainerHighestDarkHighContrast = Color(0xFF43474F)















